### ISSUE TITLE
Can this library manually input camera internal parameters

### ISSUE THREAD

**Issue by HongxiZhao** [marlam/camsim-mirror#1]

**Comment by HongxiZhao** [comment]
Can this library manually input camera internal parameters？

**Comment by marlam** [comment]
You can set camera intrinsics [via Projection](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_projection.html), including distortion parameters, Time-of-Flight parameters [via PMD](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_p_m_d.html), and various simulation parameters [via Pipeline](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_pipeline.html).

**Comment by HongxiZhao** [comment]
Thank you a lot

> You can set camera intrinsics [via Projection](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_projection.html), including distortion parameters, Time-of-Flight parameters [via PMD](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_p_m_d.html), and various simulation parameters [via Pipeline](https://marlam.de/camsim/libcamsim-reference/class_cam_sim_1_1_pipeline.html).
